#!/bin/bash
#############################################################################################################
# Script Name: buccaneer.sh
# Description: This script runs Buccaneer for automated model building after Molecular Replacement (MR).
#
# Workflow:
#   1. Create directories for Buccaneer processing.
#   2. For each MR solution in PHASER_MR/MR_SUMMARY:
#        - Identify the best PDB model (REFINEMENT/XYZOUT.pdb or PHASER.1.pdb).
#        - Select the corresponding MTZ file (PHASER.1.mtz or other MTZ in the MR folder).
#        - Run i2_buccaneer.sh in background for model building.
#   3. Wait for all Buccaneer jobs to finish.
#   4. Collect R-work and R-free values from Buccaneer results and compare with MR refinement results.
#   5. Identify the best Buccaneer solution based on R-free (or fallback to refinement).
#   6. Copy best results to BUCCANEER_SUMMARY and the main SUMMARY folder.
#   7. Include corresponding DATA_REDUCTION logs and search models.
#
# Usage:
#   ./buccaneer.sh
#
# Inputs:
#   - MR solutions from ../PHASER_MR/MR_SUMMARY
#   - Protein sequence ($SEQUENCE provided as environment variable)
#   - MTZ and PDB files generated by Phaser MR
#
# Outputs:
#   - BUCCANEER/BUCCANEER_SUMMARY/
#       * BUCCANEER.pdb     : Best Buccaneer model
#       * BUCCANEER.mtz     : Corresponding MTZ file
#       * BUCCANEER.log     : Buccaneer log with timing and R-free summary
#   - Copies best results to ../SUMMARY for downstream steps.
#
# Dependencies:
#   - CCP4 Buccaneer
#   - i2_buccaneer.sh (internal wrapper for Buccaneer execution)
#   - Results from Phaser MR (mr.sh)
#
# Author: ZHANG Xin
# Date Created: 2023-06-01
# Last Modified: 2024-03-05
#############################################################################################################

start_time=$(date +%s)

echo ""
echo "----------------------------------------- ModelCraft -----------------------------------------"
echo ""

# Create folder for ModelCraft runs
mkdir -p MODELCRAFT
cd MODELCRAFT
mkdir -p MODELCRAFT_SUMMARY

start_dir=$(pwd)

# Run ModelCraft for each MR solution
for folder in ../PHASER_MR/MR_SUMMARY/*; do
  if [ -d "$folder" ]; then
    folder_path=$(realpath "$folder")
    folder_name=$(basename "$folder")
    mkdir -p "MODELCRAFT_${folder_name}"
    cd "MODELCRAFT_${folder_name}" || exit
    
    # Choose PDB: prefer refined model if available, fallback to Phaser output
    if [ -f "${folder_path}/REFINEMENT/XYZOUT.pdb" ]; then
        PDB=$(readlink -f "${folder_path}/REFINEMENT/XYZOUT.pdb")
    else
        PDB=$(readlink -f "${folder_path}/PHASER.1.pdb")
    fi
    
    # Choose MTZ: prefer Phaser output MTZ if available
    if [ -f "${folder_path}/PHASER.1.mtz" ]; then
        MTZ=$(readlink -f "${folder_path}/PHASER.1.mtz")
    else
        MTZ=$(find ${folder_path} -maxdepth 1 -name "*.mtz" -print -quit)
    fi
    
    # Run ModelCraft in background
    ${SOURCE_DIR}/i2_modelcraft.sh ${MTZ} ${PDB} &
    cd "$start_dir" || exit
  fi
done

# Wait for all parallel ModelCraft jobs
wait
echo "All ModelCraft processes finished!"
echo ""

cd "$start_dir" || exit

# Summarize results from all ModelCraft runs
for folder in MODELCRAFT_MR*; do
  if [ -d "$folder" ]; then
    folder_name=$(basename "$folder")
    mr_folder_name="${folder_name#*_}"
    
    # Extract R-work and R-free
    r_work=$(grep "R-work:" $folder_name/MODELCRAFT.log | tail -n 1 | awk '{print $2}' 2>/dev/null)
    r_free=$(grep "R-free:" $folder_name/MODELCRAFT.log | tail -n 1 | awk '{print $2}' 2>/dev/null)
    r_free_refine=$(grep 'FREE R VALUE                     :' "../PHASER_MR/$mr_folder_name/REFINEMENT/XYZOUT.pdb" 2>/dev/null | cut -d ':' -f 2 | xargs)
    
    echo "$folder_name: R-work=$r_work  R-free=$r_free"
    
    # Set default values for missing R-free
    r_free=${r_free:-99999}
    r_free_refine=${r_free_refine:-99999}
    
    echo "$mr_folder_name $r_free_refine $r_free" >> MODELCRAFT_SUMMARY/SUMMARY.txt
  fi
done

# Identify best ModelCraft run
best_r_free=$(sort -k3,3n "MODELCRAFT_SUMMARY/SUMMARY.txt" | awk 'NR==1 {print $3}')
best_r_free_refine=$(sort -k3,3n "MODELCRAFT_SUMMARY/SUMMARY.txt" | awk 'NR==1 {print $2}')
best_r_free=${best_r_free:-99}
best_r_free_refine=${best_r_free_refine:-99}

if [ $(echo "$best_r_free < $best_r_free_refine" | bc) -eq 1 ]; then
    best=$(sort -k3,3n "MODELCRAFT_SUMMARY/SUMMARY.txt" | awk 'NR==1 {print $1}')
else
    best=$(sort -k2,2n "MODELCRAFT_SUMMARY/SUMMARY.txt" | awk 'NR==1 {print $1}')
fi

# Copy best ModelCraft results
if [ -n "$best" ]; then
  cp "MODELCRAFT_${best}/MODELCRAFT.log" MODELCRAFT_SUMMARY/
  cp MODELCRAFT_${best}/modelcraft/* MODELCRAFT_SUMMARY/
  echo "Best R-free $best_r_free is from MODELCRAFT_${best}" | tee -a MODELCRAFT_SUMMARY/MODELCRAFT.log
  
  # Copy results to global SUMMARY
  cp MODELCRAFT_SUMMARY/* ../SUMMARY/
  cp ../PHASER_MR/MR_SUMMARY/${best}/*.* ../SUMMARY/
  cp ../PHASER_MR/MR_SUMMARY/${best}/REFINEMENT/XYZOUT.pdb ../SUMMARY/REFINEMENT.pdb
  cp ../PHASER_MR/MR_SUMMARY/${best}/REFINEMENT/FPHIOUT.mtz ../SUMMARY/REFINEMENT.mtz
  
  # Copy Data Reduction log if available
  if [ -d "../DATA_REDUCTION" ]; then
    dr_name=$(find "../PHASER_MR/MR_SUMMARY/${best}" -maxdepth 1 -type f -name "*.mtz" ! -name "PHASER.1.mtz" -exec basename {} \; | sed 's/\.mtz$//' | head -n 1)
    cp ../DATA_REDUCTION/DATA_REDUCTION_SUMMARY/${dr_name}_SUMMARY.log ../SUMMARY/
  fi
  
  
  # Copy the appropriate search models based on MR source
  if [[ "$best" == MR_A* ]]; then
    cp ../SEARCH_MODELS/AF_MODELS/* ../SUMMARY/
  elif [[ "$best" == MR_H* ]]; then
    cp ../SEARCH_MODELS/HOMOLOGS/* ../SUMMARY/
  else
    cp ../SEARCH_MODELS/INPUT_MODELS/* ../SUMMARY/
  fi
else
  echo "No valid R-free values found."
fi

# Calculate and display runtime
end_time=$(date +%s)
total_time=$((end_time - start_time))
hours=$((total_time / 3600))
minutes=$(( (total_time % 3600) / 60 ))
seconds=$((total_time % 60))

echo "" | tee -a MODELCRAFT_SUMMARY/MODELCRAFT.log
echo "ModelCraft took: ${hours}h ${minutes}m ${seconds}s" | tee -a MODELCRAFT_SUMMARY/MODELCRAFT.log

# Go to data processing folder
cd ..
